pharma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('events/', views.events_view, name="events"),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name="event"),
    path('gallery/', views.GalleryView.as_view(), name="gallery"),
    path('contact/', views.ContactView.as_view(), name="contact"),
]

poll/models.py
from enum import Enum
from django.db import models

# Create your models here.

MEDIA_CHOICES = (
    ('image', 'image'),
    ('video', 'video'),
)


class Event(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    price = models.FloatField(default=0)
    image = models.ImageField(upload_to="events")
    medias = models.ManyToManyField('Media', blank=True)
    scheduled_date = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    ticket_url = models.URLField(blank=True)

    def __str__(self):
        return self.name

    def scheduled_date_formated(self):
        return self.scheduled_date.strftime("%d/%m/%Y %H:%M")

    class Meta:
        ordering = ["-scheduled_date", "-created"]


class Media(models.Model):
    title = models.CharField(max_length=250)
    src = models.FileField(upload_to="media")
    src_type = models.CharField(
        max_length=10, choices=MEDIA_CHOICES, default='image')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created"]


class Member(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    image = models.ImageField(upload_to="members")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["created"]


class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name + " - " + self.subject

    class Meta:
        ordering = ["created"]

poll/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control'}),
        }

poll/views.py
from datetime import datetime
from django.shortcuts import redirect, render
from django.views import generic
from django.core.paginator import Paginator

from .forms import *
from .models import *

# Create your views here.


def home_view(request):
    upcoming_events = Event.objects.filter(
        scheduled_date__gte=datetime.now()).order_by('scheduled_date')[:6]
    new_images = Media.objects.filter(src_type='image')[:9]
    template = "pages/home.html"
    context = {
        "home_page": "active",
        "events": upcoming_events,
        "gallery": new_images,
    }
    return render(request, template, context)


class AboutView(generic.TemplateView):
    template_name = "pages/about.html"

    def get(self, request):
        members = Member.objects.all()
        context = {
            "about_page": "active",
            "members": members,
        }
        return render(request, self.template_name, context)


def events_view(request):
    events_list = Event.objects.all()
    paginator = Paginator(events_list, 9)

    page = request.GET.get('page')
    events = paginator.get_page(page)

    template = "pages/events.html"
    context = {
        "events_page": "active",
        "events": events
    }
    return render(request, template, context)


class EventDetailView(generic.DetailView):
    model = Event
    template_name = "pages/event.html"

    def get(self, request, *args, **kwargs):
        event = self.get_object()
        gallery = Media.objects.filter(event=event)
        context = {
            "event": event,
            "gallery": gallery,
        }
        return render(request, self.template_name, context)


class GalleryView(generic.TemplateView):
    template_name = "pages/gallery.html"

    def get(self, request):
        gallery_list = Media.objects.all()
        paginator = Paginator(gallery_list, 9)

        page = request.GET.get('page')
        gallery = paginator.get_page(page)

        context = {
            "gallery_page": "active",
            "gallery": gallery
        }
        return render(request, self.template_name, context)


class ContactView(generic.TemplateView):
    template_name = "pages/contact.html"

    def get(self, request):
        form = ContactForm()
        context = {"contact_page": "active", "form": form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            Contact.objects.create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message'],
            )
            return redirect('poll:contact')
        else:
            return render(request, self.template_name, {"contact_page": "active", "form": form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Noukaa</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

  </head>

  <body>
    <div class="site-wrap">

      {% include "components/navbar.html" %}

      {% block content %}{% endblock content %}

      {% include "components/footer.html" %}

      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/jquery-ui.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'js/aos.js' %}"></script>

      <script src="{% static 'js/main.js' %}"></script>

    </div>
  </body>

</html>

templates/components/footer.html
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

        <div class="block-7">
          <h3 class="footer-heading mb-4">About Us</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius quae reiciendis distinctio voluptates sed dolorum excepturi iure eaque, aut unde.</p>
        </div>

      </div>
      <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
        <h3 class="footer-heading mb-4">Quick Links</h3>
        <ul class="list-unstyled">
          <li>
            <a href="{% url 'poll:home' %}">Home</a>
          </li>
          <li>
            <a href="{% url 'poll:about' %}">About</a>
          </li>
          <li>
            <a href="{% url 'poll:events' %}">Events</a>
          </li>
          <li>
            <a href="{% url 'poll:gallery' %}">Gallery</a>
          </li>
          <li>
            <a href="{% url 'poll:contact' %}">Contact</a>
          </li>
        </ul>
      </div>

      <div class="col-md-6 col-lg-3">
        <div class="block-5 mb-5">
          <h3 class="footer-heading mb-4">Contact Info</h3>
          <ul class="list-unstyled">
            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
            <li class="phone">
              <a href="tel://23923929210">+91 7596976911</a>
            </li>
            <li class="email">mail@noukaa.org</li>
          </ul>
        </div>

      </div>
    </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <p>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;
          <script>
            document.write(new Date().getFullYear());
          </script>
          All rights reserved by
          <span class="text-primary">Noukaa</span>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>

    </div>
  </div>
</footer>

templates/components/navbar.html
{% load static %}

<div class="site-navbar py-2">

  <div class="search-wrap">
    <div class="container">
      <a href="#" class="search-close js-search-close">
        <span class="icon-close2"></span></a>
      <form action="#" method="post">
        <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
      </form>
    </div>
  </div>

  <div class="container">
    <div class="d-flex align-items-center justify-content-between">
      <div class="logo">
        <div class="site-logo">

          <a href="{% url 'poll:home' %}" class="js-logo-clone"><img src="{% static 'images/logo.png' %}" height="70" width="70" alt=""></a>
        </div>
      </div>
      <div class="main-nav d-none d-lg-block">
        <nav class="site-navigation text-right text-md-center" role="navigation">
          <ul class="site-menu js-clone-nav d-none d-lg-block">
            <li class="{{ home_page }}">
              <a href="{% url 'poll:home' %}">Home</a>
            </li>
            <li class="{{ about_page }}">
              <a href="{% url 'poll:about' %}">About</a>
            </li>
            <li class="{{ events_page }}">
              <a href="{% url 'poll:events' %}">Events</a>
            </li>
            <li class="{{ gallery_page }}">
              <a href="{% url 'poll:gallery' %}">Gallery</a>
            </li>
            <li class="{{ contact_page }}">
              <a href="{% url 'poll:contact' %}">Contact</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="icons">
        <a href="#" class="icons-btn d-inline-block js-search-open">
          <span class="icon-search"></span></a>
        <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none">
          <span class="icon-menu"></span></a>
      </div>
    </div>
  </div>
</div>

templates/components/navigation.html
<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0">
        <a href="{% url 'poll:home' %}">Home</a>
        <span class="mx-2 mb-0">/</span>
        <strong class="text-black">
          {% if events_page %}
            Events
          {% elif gallery_page %}
            Gallery
          {% elif contact_page %}
            Contact
          {% endif %}
        </strong>
      </div>
    </div>
  </div>
</div>

templates/components/pre-footer.html
{% load static %}

<style>
  .banner1-background {
    background-image: url("{% static 'images/bg_1.jpg' %}");
  }

  .banner2-background {
    background-image: url("{% static 'images/bg_2.jpg' %}");
  }

  .social-img {
    max-width: 100%;
  }
</style>

<div class="site-section bg-secondary bg-image banner2-background">
  <div class="container">
    <div class="row align-items-stretch">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <a href="https://www.facebook.com/nouka.net/" class="banner-1 h-100 d-flex banner1-background">
          <div class="backdrop" style="border-radius: 4px"></div>
          <div class="banner-1-inner align-self-center position-relative">
            <img class="social-img" src="{% static 'images/facebook.webp' %}" >
            <p class="text-white">
              Please support us, Visit our facebook page.
            </p>
          </div>
        </a>
      </div>
      <div class="col-lg-6 mb-5 mb-lg-0">
        <a href="whatsapp://send?text=Hello&phone=+917596976911" class="banner-1 h-100 d-flex banner2-background">
          <div class="backdrop" style="border-radius: 4px"></div>
          <div class="banner-1-inner ml-auto align-self-center position-relative">
            <img class="social-img" src="{% static 'images/whatsapp.jpg' %}" >
            <p class="text-white">
              Say "Hello" to us on Whatsapp.
            </p>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

templates/hoc/with-banner.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  <style>
    .banner-background {
      background-image: url("{% static 'images/hero_1.jpg' %}");
    }
  </style>

  <div class="site-blocks-cover banner-background">
    <div class="backdrop"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
          <div class="site-block-cover-content text-center">
            {% block banner %}{% endblock banner %}
          </div>
        </div>
      </div>
    </div>
  </div>

  {% block main %}{% endblock main %}

{% endblock content %}

templates/pages/about.html
{% extends "hoc/with-banner.html" %}

{% load static %}

{% block banner %}

  <h1>About Us</h1>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum obcaecati natus iure voluptatum eveniet harum recusandae ducimus saepe.</p>

{% endblock banner %}

{% block main %}

  <div class="site-section bg-light custom-border-bottom" data-aos="fade">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6">
          <div class="block-16">
            <figure>
              <img src="{% static 'images/bg_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo">
                <span class="icon-play"></span></a>

            </figure>
          </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-5">

          <div class="site-section-heading pt-3 mb-4">
            <h2 class="text-black">How We Started</h2>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.</p>
          <p>Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam cumque recusandae, laudantium minima repellendus.</p>

        </div>
      </div>
    </div>
  </div>

  <div class="site-section bg-light custom-border-bottom" data-aos="fade">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6 order-md-2">
          <div class="block-16">
            <figure>
              <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo">
                <span class="icon-play"></span></a>

            </figure>
          </div>
        </div>
        <div class="col-md-5 mr-auto">

          <div class="site-section-heading pt-3 mb-4">
            <h2 class="text-black">We Are Trusted Company</h2>
          </div>
          <p class="text-black">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.</p>
          <p class="text-black">Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam cumque recusandae, laudantium minima repellendus.</p>

        </div>
      </div>
    </div>
  </div>

  <div class="site-section site-section-sm site-blocks-1 border-0" data-aos="fade">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
          <div class="icon mr-4 align-self-start">
            <span class="icon-truck text-primary"></span>
          </div>
          <div class="text">
            <h2>Free Shipping</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
          <div class="icon mr-4 align-self-start">
            <span class="icon-refresh2 text-primary"></span>
          </div>
          <div class="text">
            <h2>Free Returns</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
          <div class="icon mr-4 align-self-start">
            <span class="icon-help text-primary"></span>
          </div>
          <div class="text">
            <h2>Customer Support</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="team" class="site-section bg-light custom-border-bottom" data-aos="fade">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 site-section-heading text-center pt-4">
          <h2>The Team</h2>
        </div>
      </div>
      <div class="row">
        {% for member in members %}
          <div class="col-md-6 col-lg-4 mb-5">

            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{{ member.image.url }}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">{{ member.name }}</h3>
                  <p class="block-38-subheading">{{ member.description }}</p>
                </div>
                {% comment %} <div class="block-38-body">
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta.
                  </p>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock main %}

templates/pages/contact.html
{% extends "base.html" %}

{% block content %}

  {% include "components/navigation.html" %}

  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="h3 mb-5 text-black">Get In Touch</h2>
        </div>
        <div class="col-md-12">

          <form action="#" method="post">

            <div class="p-3 p-lg-5 border">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="form-group row">
                <div class="col-lg-12">
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </div>
              </div>
            </div>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="site-section bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-white mb-4">Offices</h2>
        </div>
        <div class="col-lg-4">
          <div class="p-4 bg-white mb-3 rounded">
            <span class="d-block text-black h6 text-uppercase">New York</span>
            <p class="mb-0">203 Fake St. Mountain View, San Francisco, California, USA</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="p-4 bg-white mb-3 rounded">
            <span class="d-block text-black h6 text-uppercase">London</span>
            <p class="mb-0">203 Fake St. Mountain View, San Francisco, California, USA</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="p-4 bg-white mb-3 rounded">
            <span class="d-block text-black h6 text-uppercase">Canada</span>
            <p class="mb-0">203 Fake St. Mountain View, San Francisco, California, USA</p>
          </div>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

templates/pages/events.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  {% include "components/navigation.html" %}

  <div class="site-section">
    <div class="container">
      <div class="row">
        {% for event in events %}
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <a href="{% url 'poll:event' event.pk %}">
              <img width="275" height="180" src="{{ event.image.url }}" alt="Image"/></a>
            <h3 class="text-dark">
              <a href="shop-single.html">{{ event.name }}</a>
            </h3>
            <p class="text-sm my-2">{{ event.scheduled_date_formated }}</p>
            <p class="price">₹{{ event.price }}</p>
          </div>
        {% endfor %}
      </div>
      <div class="row mt-5">
        <div class="col-md-12 text-center">
          <div class="site-block-27">
            <ul>
              {% if events.has_previous %}
                <li>
                  <a href="?page=1">&laquo;</a>
                </li>
                <li>
                  <a href="?page={{ events.previous_page_number }}">&lt;</a>
                </li>
              {% endif %}

              <li class="active">
                <span>{{ events.number }}</span></li>

              {% if events.has_next %}
                <li>
                  <a href="?page={{ events.next_page_number }}">{{ events.next_page_number }}</a>
                </li>
                <li>
                  <a href="?page={{ events.paginator.num_pages }}">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "components/pre-footer.html" %}

{% endblock content %}

templates/pages/home.html
{% extends "hoc/with-banner.html" %}

{% load static %}

{% block banner %}

  <h2 class="sub-title">
    Clean White and Black, no confused shades of grey, Noukaa is a reality, no more no less.
  </h2>
  <h1>Welcome To Noukaa</h1>
  <p>
    <a href="{% url 'poll:contact' %}" class="btn btn-primary px-5 py-3">Join Us</a>
  </p>

{% endblock banner %}

{% block main %}

  <div class="site-section">
    <div class="container">
      <div class="row align-items-stretch section-overlap">
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap bg-primary h-100">
            <a href="https://rzp.io/l/CN3rhPh" class="h-100">
              <h5>
                Donate
              </h5>
              <p>
                Our mission is to help children in need.
              </p>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap h-100">
            <a href="{% url 'poll:about' %}#team" class="h-100">
              <h5>
                Our Team
              </h5>
              <p>
                We are a team of passionate people who love to help others.
              </p>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap bg-warning h-100">
            <a href="#" class="h-100">
              <h5>
                Notice Board
              </h5>
              <p>
                View our latest news and updates.
              </p>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Upcoming Events</h2>
        </div>
      </div>

      <div class="row">
        {% for event in events %}
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <a href="shop-single.html">
              <img width="275" height="180" src="{{ event.image.url }}" alt="Image"/></a>
            <h3 class="text-dark">
              <a href="shop-single.html">{{ event.name }}</a>
            </h3>
            <p class="text-sm my-2">{{ event.scheduled_date_formated }}</p>
            <p class="price">₹{{ event.price }}</p>
          </div>
        {% endfor %}
      </div>
      <div class="row mt-5">
        <div class="col-12 text-center">
          <a href="{% url 'poll:events' %}" class="btn btn-primary px-4 py-3">View All Events</a>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section bg-light">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Our Gallery</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 block-3 products-wrap">
          <div class="nonloop-block-3 owl-carousel">
            {% for image in gallery %}
              <div class="text-center item mb-4">
                <a href="shop-single.html">
                  <img width="350" height="230" src="{{ image.src.url }}" alt="Image"/></a>
                <h3 class="text-dark">
                  <a href="shop-single.html">{{ image.title }}</a>
                </h3>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Testimonials</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 block-3 products-wrap">
          <div class="nonloop-block-3 no-direction owl-carousel">
            <div class="testimony">
              <blockquote>
                <img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle"/>
                <p>
                  &ldquo;Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo omnis voluptatem consectetur quam tempore obcaecati maiores voluptate aspernatur iusto eveniet, placeat ab quod tenetur ducimus. Minus ratione sit quaerat unde.&rdquo;
                </p>
              </blockquote>

              <p>&mdash; Kelly Holmes</p>
            </div>

            <div class="testimony">
              <blockquote>
                <img src="{% static 'images/person_2.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle"/>
                <p>
                  &ldquo;Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo omnis voluptatem consectetur quam tempore obcaecati maiores voluptate aspernatur iusto eveniet, placeat ab quod tenetur ducimus. Minus ratione sit quaerat unde.&rdquo;
                </p>
              </blockquote>

              <p>&mdash; Rebecca Morando</p>
            </div>

            <div class="testimony">
              <blockquote>
                <img src="{% static 'images/person_3.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle"/>
                <p>
                  &ldquo;Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo omnis voluptatem consectetur quam tempore obcaecati maiores voluptate aspernatur iusto eveniet, placeat ab quod tenetur ducimus. Minus ratione sit quaerat unde.&rdquo;
                </p>
              </blockquote>

              <p>&mdash; Lucas Gallone</p>
            </div>

            <div class="testimony">
              <blockquote>
                <img src="{% static 'images/person_4.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle"/>
                <p>
                  &ldquo;Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo omnis voluptatem consectetur quam tempore obcaecati maiores voluptate aspernatur iusto eveniet, placeat ab quod tenetur ducimus. Minus ratione sit quaerat unde.&rdquo;
                </p>
              </blockquote>

              <p>&mdash; Andrew Neel</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "components/pre-footer.html" %}

{% endblock main %}